// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProxmoxControl.Data;

#nullable disable

namespace ProxmoxControl.Migrations
{
    [DbContext(typeof(ProxmoxControlDbContext))]
    partial class ProxmoxControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ProxmoxControl.Data.RegisteredChat", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxmoxApiToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProxmoxHost")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("RegisteredChats");
                });
#pragma warning restore 612, 618
        }
    }
}
